In [9]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [10]:
print(application_df.columns)

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [11]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
print(application_df.head())

  APPLICATION_TYPE       AFFILIATION CLASSIFICATION      USE_CASE  \
0              T10       Independent          C1000    ProductDev
1               T3       Independent          C2000  Preservation
2               T5  CompanySponsored          C3000    ProductDev
3               T3  CompanySponsored          C2000  Preservation
4               T3       Independent          C1000     Heathcare

   ORGANIZATION  STATUS     INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  \
0   Association       1              0                      N     5000
1  Co-operative       1         1-9999                      N   108590
2   Association       1              0                      N     5000
3         Trust       1    10000-24999                      N     6692
4         Trust       1  100000-499999                      N   142590

   IS_SUCCESSFUL
0              1
1              1
2              0
3              1
4              1

In [12]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [13]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
atype_counts = (application_df['APPLICATION_TYPE'].value_counts())
atype_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [14]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(atype_counts[atype_counts<500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [15]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_counts = (application_df['CLASSIFICATION'].value_counts())
class_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [16]:
# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = class_counts[class_counts>1]
countsclassification

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [17]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts<100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [18]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [19]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(['IS_SUCCESSFUL'], axis=1)
y = application_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [20]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 1

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                4000

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6461 (25.24 KB)
Trainable params: 6461 (25.24 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [22]:
# Compile the model
nn_model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [23]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 3s 3ms/step - loss: 0.5751 - accuracy: 0.7163 - val_loss: 0.5472 - val_accuracy: 0.7370
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5558 - accuracy: 0.7260 - val_loss: 0.5435 - val_accuracy: 0.7313
Epoch 3/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5520 - accuracy: 0.7285 - val_loss: 0.5434 - val_accuracy: 0.7346
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7286 - val_loss: 0.5446 - val_accuracy: 0.7344
Epoch 5/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7312 - val_loss: 0.5445 - val_accuracy: 0.7346
Epoch 6/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7314 - val_loss: 0.5410 - val_accuracy: 0.7367
Epoch 7/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7319 - val_loss: 0.5425 - val_accuracy: 0.7362
Epoch 8/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7317 - val_loss: 0.5463 - val_accuracy: 0.7365
Epoch 9/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7319 - val_loss: 0.5420 - val_accuracy: 0.7349
Epoch 10/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7328 - val_loss: 0.5409 - val_accuracy: 0.7362
Epoch 11/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5442 - accuracy: 0.7336 - val_loss: 0.5415 - val_accuracy: 0.7362
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7334 - val_loss: 0.5458 - val_accuracy: 0.7328
Epoch 13/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7318 - val_loss: 0.5423 - val_accuracy: 0.7375
Epoch 14/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7322 - val_loss: 0.5420 - val_accuracy: 0.7357
Epoch 15/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7339 - val_loss: 0.5407 - val_accuracy: 0.7370
Epoch 16/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7360 - val_loss: 0.5411 - val_accuracy: 0.7359
Epoch 17/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7354 - val_loss: 0.5415 - val_accuracy: 0.7367
Epoch 18/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7352 - val_loss: 0.5458 - val_accuracy: 0.7349
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7363 - val_loss: 0.5431 - val_accuracy: 0.7383
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7373 - val_loss: 0.5449 - val_accuracy: 0.7297
Epoch 21/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7336 - val_loss: 0.5398 - val_accuracy: 0.7359
Epoch 22/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7351 - val_loss: 0.5464 - val_accuracy: 0.7341
Epoch 23/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7361 - val_loss: 0.5416 - val_accuracy: 0.7352
Epoch 24/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7357 - val_loss: 0.5439 - val_accuracy: 0.7362
Epoch 25/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7367 - val_loss: 0.5427 - val_accuracy: 0.7359
Epoch 26/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7355 - val_loss: 0.5388 - val_accuracy: 0.7375
Epoch 27/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7365 - val_loss: 0.5415 - val_accuracy: 0.7367
Epoch 28/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7368 - val_loss: 0.5417 - val_accuracy: 0.7323
Epoch 29/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7363 - val_loss: 0.5409 - val_accuracy: 0.7354
Epoch 30/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7360 - val_loss: 0.5426 - val_accuracy: 0.7357
Epoch 31/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7365 - val_loss: 0.5440 - val_accuracy: 0.7370
Epoch 32/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7377 - val_loss: 0.5442 - val_accuracy: 0.7344
Epoch 33/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7369 - val_loss: 0.5414 - val_accuracy: 0.7383
Epoch 34/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7365 - val_loss: 0.5442 - val_accuracy: 0.7344
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7379 - val_loss: 0.5426 - val_accuracy: 0.7380
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7374 - val_loss: 0.5435 - val_accuracy: 0.7367
Epoch 37/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7383 - val_loss: 0.5412 - val_accuracy: 0.7393
Epoch 38/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7384 - val_loss: 0.5431 - val_accuracy: 0.7354
Epoch 39/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7373 - val_loss: 0.5411 - val_accuracy: 0.7365
Epoch 40/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7375 - val_loss: 0.5419 - val_accuracy: 0.7372
Epoch 41/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7380 - val_loss: 0.5439 - val_accuracy: 0.7362
Epoch 42/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7376 - val_loss: 0.5418 - val_accuracy: 0.7365
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7378 - val_loss: 0.5442 - val_accuracy: 0.7375
Epoch 44/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5358 - accuracy: 0.7378 - val_loss: 0.5415 - val_accuracy: 0.7362
Epoch 45/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7377 - val_loss: 0.5435 - val_accuracy: 0.7380
Epoch 46/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7377 - val_loss: 0.5463 - val_accuracy: 0.7352
Epoch 47/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7382 - val_loss: 0.5454 - val_accuracy: 0.7372
Epoch 48/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7383 - val_loss: 0.5433 - val_accuracy: 0.7357
Epoch 49/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7384 - val_loss: 0.5422 - val_accuracy: 0.7365
Epoch 50/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7385 - val_loss: 0.5452 - val_accuracy: 0.7336
Epoch 51/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7386 - val_loss: 0.5453 - val_accuracy: 0.7359
Epoch 52/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7386 - val_loss: 0.5437 - val_accuracy: 0.7378
Epoch 53/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7390 - val_loss: 0.5446 - val_accuracy: 0.7375
Epoch 54/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7378 - val_loss: 0.5426 - val_accuracy: 0.7339
Epoch 55/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7385 - val_loss: 0.5442 - val_accuracy: 0.7372
Epoch 56/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7385 - val_loss: 0.5441 - val_accuracy: 0.7354
Epoch 57/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7390 - val_loss: 0.5424 - val_accuracy: 0.7359
Epoch 58/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7382 - val_loss: 0.5465 - val_accuracy: 0.7378
Epoch 59/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7392 - val_loss: 0.5430 - val_accuracy: 0.7359
Epoch 60/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5354 - accuracy: 0.7389 - val_loss: 0.5431 - val_accuracy: 0.7375
Epoch 61/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7385 - val_loss: 0.5416 - val_accuracy: 0.7370
Epoch 62/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7378 - val_loss: 0.5435 - val_accuracy: 0.7367
Epoch 63/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7389 - val_loss: 0.5440 - val_accuracy: 0.7370
Epoch 64/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7385 - val_loss: 0.5417 - val_accuracy: 0.7367
Epoch 65/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7382 - val_loss: 0.5449 - val_accuracy: 0.7367
Epoch 66/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7395 - val_loss: 0.5457 - val_accuracy: 0.7354
Epoch 67/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7394 - val_loss: 0.5428 - val_accuracy: 0.7352
Epoch 68/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5346 - accuracy: 0.7381 - val_loss: 0.5441 - val_accuracy: 0.7378
Epoch 69/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7384 - val_loss: 0.5424 - val_accuracy: 0.7375
Epoch 70/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7385 - val_loss: 0.5424 - val_accuracy: 0.7380
Epoch 71/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7402 - val_loss: 0.5420 - val_accuracy: 0.7370
Epoch 72/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7391 - val_loss: 0.5419 - val_accuracy: 0.7362
Epoch 73/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7390 - val_loss: 0.5433 - val_accuracy: 0.7370
Epoch 74/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7392 - val_loss: 0.5442 - val_accuracy: 0.7370
Epoch 75/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7401 - val_loss: 0.5454 - val_accuracy: 0.7346
Epoch 76/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5335 - accuracy: 0.7401 - val_loss: 0.5479 - val_accuracy: 0.7336
Epoch 77/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5335 - accuracy: 0.7393 - val_loss: 0.5442 - val_accuracy: 0.7341
Epoch 78/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7410 - val_loss: 0.5436 - val_accuracy: 0.7362
Epoch 79/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7408 - val_loss: 0.5418 - val_accuracy: 0.7365
Epoch 80/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7402 - val_loss: 0.5431 - val_accuracy: 0.7375
Epoch 81/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7395 - val_loss: 0.5456 - val_accuracy: 0.7359
Epoch 82/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7397 - val_loss: 0.5449 - val_accuracy: 0.7357
Epoch 83/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7405 - val_loss: 0.5436 - val_accuracy: 0.7344
Epoch 84/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7402 - val_loss: 0.5462 - val_accuracy: 0.7367
Epoch 85/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7392 - val_loss: 0.5466 - val_accuracy: 0.7357
Epoch 86/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7396 - val_loss: 0.5458 - val_accuracy: 0.7362
Epoch 87/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7404 - val_loss: 0.5460 - val_accuracy: 0.7370
Epoch 88/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7407 - val_loss: 0.5452 - val_accuracy: 0.7362
Epoch 89/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7396 - val_loss: 0.5458 - val_accuracy: 0.7359
Epoch 90/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7398 - val_loss: 0.5456 - val_accuracy: 0.7352
Epoch 91/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7400 - val_loss: 0.5463 - val_accuracy: 0.7365
Epoch 92/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7404 - val_loss: 0.5466 - val_accuracy: 0.7378
Epoch 93/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7399 - val_loss: 0.5486 - val_accuracy: 0.7367
Epoch 94/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7397 - val_loss: 0.5453 - val_accuracy: 0.7367
Epoch 95/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7394 - val_loss: 0.5461 - val_accuracy: 0.7378
Epoch 96/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7403 - val_loss: 0.5436 - val_accuracy: 0.7372
Epoch 97/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7401 - val_loss: 0.5447 - val_accuracy: 0.7352
Epoch 98/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7405 - val_loss: 0.5458 - val_accuracy: 0.7362
Epoch 99/100
684/684 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7396 - val_loss: 0.5456 - val_accuracy: 0.7365
Epoch 100/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7408 - val_loss: 0.5491 - val_accuracy: 0.7349

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5610 - accuracy: 0.7283 - 342ms/epoch - 1ms/step
Loss: 0.5609740018844604, Accuracy: 0.7282798886299133

In [25]:
# Export our model to HDF5 file
from keras.models import load_model

# Save the model to an HDF5 file
nn_model.save("AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [26]:
import os
os.getcwd